
spotify_mlops/spotify_mlops:v0
15-02-2022 16:54:01 Downloading artifact
Traceback (most recent call last):
  File "/home/mariana/spotify-mlops/preprocess/run.py", line 106, in <module>
    process_args(ARGS)
  File "/home/mariana/spotify-mlops/preprocess/run.py", line 46, in process_args
    df.drop(columns=['key', 'uri', 'track_href', 'analysis_url', 'id', 'time_signature',
  File "/home/mariana/anaconda3/envs/mlflow-a054d55a40965e07293b22508500504e2500fd05/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/mariana/anaconda3/envs/mlflow-a054d55a40965e07293b22508500504e2500fd05/lib/python3.10/site-packages/pandas/core/frame.py", line 4906, in drop
    return super().drop(
  File "/home/mariana/anaconda3/envs/mlflow-a054d55a40965e07293b22508500504e2500fd05/lib/python3.10/site-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/mariana/anaconda3/envs/mlflow-a054d55a40965e07293b22508500504e2500fd05/lib/python3.10/site-packages/pandas/core/generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/mariana/anaconda3/envs/mlflow-a054d55a40965e07293b22508500504e2500fd05/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['key' 'uri' 'track_href' 'analysis_url' 'id' 'time_signature' 'song_name'\n 'Unnamed: 0' 'title' 'type' 'mode'] not found in axis"
./artifacts/spotify_mlops:v0/spotify_mlops
Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            19, 20, 21],
           dtype='int64')